dataset_params:
  name: AllenStaticGratingsLoader
  snr_threshold: 4
  bin_edges: [0.0, 0.2]

model_params:
  seed: 0

  gp_kernel:
    - x1:
      type: RBF
      diag: 0.0001
      scale: 10
      sigma: 5

  wp_kernel:
    - x1: 
      type: RBF
      diag: 0.0001
      scale: 10
      sigma: 5
      nu: 10

variational_params:
  guide: Normal
  num_particles: 10

  optimizer:
    type: adam
    step_size: 0.1

visualization_params:
  - plot_tuning
  - visualize_pc
  - plot_loss
  - plot_box