load: False

dataset_params:
  name: AllenStaticGratingsLoader
  snr_threshold: 4
  bin_edges: [0.0, 0.2]
  selector: conditions[i]['spatial_freq'] == 0.02 # 'True'
  train_trial_prop: .9
  train_condition_prop: 1.
  seed: 1


model_params:
  seed: 2
  nu: 3
  optimize_L: True
  gp_kernel_diag: 0.001
  gp_kernel:
    - type: periodic
      sigma: 1.
      scale: 1.
      normalizer: 180
    
    - type: periodic
      sigma: .1
      scale: 1.
      normalizer: 1

  wp_sample_diag: .1

  wp_kernel_diag: 0.001
  wp_kernel:
    - type: periodic
      sigma: 1.
      scale: .1
      normalizer: 180
      
    - type: periodic
      sigma: 0.1
      scale: .1
      normalizer: 1

  likelihood: NormalConditionalLikelihood # likelihood model

variational_params:
  guide: VariationalNormal # VariationalNormal/VariationalDelta
  num_particles: 1 # number of importance weighting particles
  n_iter: 50000 # number of optimization iterations

  optimizer:
    type: Adam
    step_size: 0.001

visualization_params:
  - visualize_pc
  - plot_loss
  - plot_box