dataset_params:
  name: AllenStaticGratingsLoader
  snr_threshold: 4
  bin_edges: [0.0, 0.2]
  selector: conditions[i]['spatial_freq'] == 0.02 # 'True'
  train_trial_prop: .8
  train_condition_prop: .9


model_params:
  seed: 0
  nu: 100
  optimize_L: False
  gp_kernel:
    - type: periodic
      diag: 0.01
      scale: 1
      sigma: .5
      normalizer: 180
    
    - type: periodic
      diag: 0.01
      scale: 1
      sigma: .5
      normalizer: 1

    # - type: RBF
    #   diag: 0.01
    #   scale: 10
    #   sigma: 10.

  wp_kernel:
    - type: periodic
      diag: .01
      scale: 1. #10
      sigma: 5.5
      normalizer: 180

    - type: periodic
      diag: .01
      scale: 1. #10
      sigma: 5.5
      normalizer: 1

    # - type: RBF
    #   diag: 0.01
    #   scale: 1000.
    #   sigma: 1000.

  likelihood: NormalConditionalLikelihood # likelihood model

variational_params:
  guide: VariationalNormal # VariationalNormal/VariationalDelta
  num_particles: 1 # number of importance weighting particles
  n_iter: 50000 # number of optimization iterations

  optimizer:
    type: Adam
    step_size: 0.001

visualization_params:
  - visualize_pc
  - plot_loss
  - plot_box