load: False

dataset_params:
  name: AllenStaticGratingsLoader
  gratings: drifting
  snr_threshold: 4
  bin_edges: [0.0, 0.2]
  selector: 'True'
  train_trial_prop: .9
  train_condition_prop: 1.
  seed: 0
  # representation: direction

model_params:
  seed: 1
  nu: 0
  optimize_L: False

  gp_kernel_diag: 0.001
  gp_kernel:
    - type: periodic
      scale: 2.
      sigma: 1.
      normalizer: 180

    - type: RBF
      scale: 2.
      sigma: .1
      normalizer: 15.

    - type: periodic
      scale: 2.
      sigma: 10.
      normalizer: 2.

  wp_sample_diag: 1.

  wp_kernel_diag: 0.001
  wp_kernel:
    - type: periodic
      scale: 1.
      sigma: 2.
      normalizer: 180

    - type: RBF
      scale: 1.
      sigma: .1
      normalizer: 15.
      
    - type: periodic
      scale: 1.
      sigma: 100.
      normalizer: 2.

  likelihood: NormalConditionalLikelihood # likelihood model

variational_params:
  guide: VariationalNormal # VariationalNormal/VariationalDelta
  num_particles: 1 # number of importance weighting particles
  n_iter: 50000 # number of optimization iterations

  optimizer:
    type: Adam
    step_size: 0.001

visualization_params:
  - visualize_pc
  - plot_loss
  - plot_box