dataset_params:
  name: AllenStaticGratingsLoader
  snr_threshold: 4
  bin_edges: [0.0, 0.2]
  selector: conditions[i]['spatial_freq'] == 0.08 # 
  train_prop: 0.8

model_params:
  seed: 0
  nu_scale: 4
  optimize_L: True
  gp_kernel:
    - type: periodic
      diag: 0.01
      scale: 50
      sigma: .1
    
    - type: periodic
      diag: 0.01
      scale: 50
      sigma: 0.0008

    # - type: RBF
    #   diag: 0.01
    #   scale: 10
    #   sigma: 10.

  wp_kernel:
    - type: periodic
      diag: .01
      scale: .01
      sigma: .05

    - type: periodic
      diag: .01
      scale: .01
      sigma: 0.0004

    # - type: RBF
    #   diag: 0.01
    #   scale: 1000.
    #   sigma: 1000.

  likelihood: NormalConditionalLikelihood # likelihood model

variational_params:
  guide: VariationalNormal # VariationalNormal/VariationalDelta
  num_particles: 1 # number of importance weighting particles
  n_iter: 20000 # number of optimization iterations

  optimizer:
    type: Adam
    step_size: 0.01

visualization_params:
  - visualize_pc
  - plot_loss
  - plot_box