# dataset parameters
# ==================
load: False

dataset_params:
  name: GPWPLoader
  D: 100 # dimension/number of neurons
  M: 40 # number of conditions
  N: 10 # number of trials per condition
  
  scale_type: diag
  # rank: 2
  epsilon: 1. #.1 # scale matrix is epsilon*np.eye(D)

  train_trial_prop: .8 # proportion of training and testing trials per condition
  train_condition_prop: .8 # proportion of training and testing conditions

  seed: 0 # generative seed (can be different from inference seed)

  prior: WishartProcess
  nu: 4 # degrees of freedom for the generative model
  
  gp_kernel_diag: 0.001
  gp_kernel: # inference gaussian process kernel parameters
    - type: periodic 
      scale: 1
      sigma: 1.
      normalizer: 360

  wp_sample_diag: .1

  wp_kernel_diag: 0.001
  wp_kernel: # generative wishart process parameters (a list with one kernel per condition dimension)
    - type: periodic # periodic/RBF are implemented
      scale: 1
      sigma: 1. # kernel spread
      normalizer: 360

  likelihood: NormalConditionalLikelihood
      
# model parameters
# ================
model_params:
  prior: WishartProcess
  seed: 1 # inference seed
  nu: 4 # degrees of freedom for the inference model

  gp_kernel_diag: 0.001
  gp_kernel: # inference gaussian process kernel parameters
    - type: periodic 
      scale: 1
      sigma: 1.
      normalizer: 360

  wp_sample_diag: .1
  
  optimize_L: True
  wp_kernel_diag: 0.001
  wp_kernel: # infernce wishart process kernel parameters
    - type: periodic      
      scale: 1
      sigma: 1.
      normalizer: 360

  likelihood: NormalConditionalLikelihood # likelihood model
      
# inference parameters
# ====================
variational_params:
  guide: VariationalNormal # VariationalNormal/VariationalDelta
  num_particles: 1 # number of importance weighting particles
  n_iter: 50000 # number of optimization iterations

  optimizer:
    type: Adam # Adam/SGD
    step_size: 0.001

# comparison parameters
# =====================
comparison_params:
  n_components: 2 # Factor Analysis comparison
  shrinkage: 0.01 # PoSCE comparison
  alpha: 0.1 # Graphical Lasso comparison

# visualization parameters
# ========================
visualization_params:
  - plot_tuning # plot tuning of data to training conditions
  - visualize_pc # plot point clouds in the PC space
  - plot_loss # plot loss
  - plot_box # plot log likelihood and operator norm comparisons