load: False

dataset_params:
  name: MonkeyReachLoader
  session: /mnt/home/anejatbakhsh/Desktop/Projects/Wishart-Process/data/EvenChenSheffer-2019/3-rings/r_2016-01-28_1.mat
  #
  
  window: 200

  train_trial_prop: .9
  train_condition_prop: 1.

  sqrt_transform: True
  
  seed: 0
  representation: polar # cartesian or cartesian
  selector: (abs(conditions[i]['r']) > 1e-6) # & (abs(conditions[i]['r']) < 100)

model_params:
  seed: 2
  nu: 0
  optimize_L: False

  gp_kernel_diag: 0.001
  gp_kernel:
    - type: periodic
      scale: 1.
      sigma: 2.
      normalizer: 360

    - type: RBF
      scale: 1.
      sigma: .1
      normalizer: 120.

  wp_sample_diag: 1.

  wp_kernel_diag: 0.001
  wp_kernel:
    - type: periodic
      scale: 1.
      sigma: 3.
      normalizer: 360

    - type: RBF
      scale: 1.
      sigma: .1
      normalizer: 120.

  likelihood: NormalConditionalLikelihood # likelihood model

variational_params:
  guide: VariationalNormal # VariationalNormal/VariationalDelta
  num_particles: 1 # number of importance weighting particles
  n_iter: 50000 # number of optimization iterations

  optimizer:
    type: Adam
    step_size: 0.001

visualization_params:
  - visualize_pc
  - plot_loss
  - plot_box