load: False

dataset_params:
  name: MonkeyReachLoader
  session: /mnt/home/anejatbakhsh/Desktop/Projects/Wishart-Process/data/EvenChenSheffer-2019/3-rings/r_2016-01-29_1.mat
  window: 400

  train_trial_prop: .8
  train_condition_prop: .9
  
  seed: 0
  representation: polar # cartesian or cartesian
  selector: (abs(conditions[i]['r']) > 1e-6) & (abs(conditions[i]['r']) < 50)

model_params:
  seed: 0
  nu: 100
  optimize_L: False

  gp_kernel_diag: 0.001
  gp_kernel:
    - type: periodic
      scale: .1
      sigma: .1
      normalizer: 360

    - type: RBF
      scale: 10
      sigma: 100.

  wp_kernel_diag: 0.001
  wp_kernel:
    - type: periodic
      scale: 1. #10
      sigma: 4.5
      normalizer: 360

    - type: RBF
      scale: 1.
      sigma: 100.

  likelihood: NormalConditionalLikelihood # likelihood model

variational_params:
  guide: VariationalNormal # VariationalNormal/VariationalDelta
  num_particles: 1 # number of importance weighting particles
  n_iter: 50000 # number of optimization iterations

  optimizer:
    type: Adam
    step_size: 0.001

visualization_params:
  - visualize_pc
  - plot_loss
  - plot_box