# dataset parameters
# ==================
load: False

dataset_params:
  name: GPWPLoader
  D: 10 # dimension/number of neurons
  M: 30 # number of conditions
  N: 50 # number of trials per condition
  
  scale_type: exp_decay_eig
  epsilon: .1 #.1 # scale matrix is epsilon*np.eye(D)

  train_trial_prop: .8 # proportion of training and testing trials per condition
  train_condition_prop: 1 # proportion of training and testing conditions

  seed: 1 # generative seed (can be different from inference seed)

  prior: WishartGammaProcess
  nu: 2 # degrees of freedom for the generative model
  
  gp_kernel_diag: 0.001
  gp_kernel: # inference gaussian process kernel parameters
    - type: periodic 
      sigma: 1.
      scale: 1
      normalizer: 360

  wp_sample_diag: 1.

  wp_kernel_diag: 0.001
  wp_kernel: # generative wishart process parameters (a list with one kernel per condition dimension)
    - type: periodic # periodic/RBF are implemented
      sigma: 1. # kernel spread
      scale: 1.
      normalizer: 360

  likelihood: PoissonConditionalLikelihood
  likelihood_params:
    rate: [1.,1.,1.,1.,1.,1.,1.,1.,1.,1.]
          
# model parameters
# ================
model_params:
  seed: 0 # inference seed

  prior: WishartGammaProcess
  nu: 2 # degrees of freedom for the inference model

  gp_kernel_diag: 0.001
  gp_kernel: # inference gaussian process kernel parameters
    - type: periodic 
      sigma: 1.
      scale: 1
      normalizer: 360
    
  wp_sample_diag: 1.
  
  wp_kernel_diag: 0.001
  wp_kernel: # infernce wishart process kernel parameters
    - type: periodic
      sigma: 1.
      scale: 1.
      normalizer: 360

  likelihood: PoissonConditionalLikelihood # likelihood model
  likelihood_params:
    rate: [.1,.1,.1,.1,.1,.1,.1,.1,.1,.1]
      
# inference parameters
# ====================
variational_params:
  guide: VariationalDelta # VariationalNormal/VariationalDelta
  num_particles: 1 # number of importance weighting particles
  n_iter: 50000 # number of optimization iterations

  optimizer:
    type: Adam # Adam/SGD
    step_size: 0.1

# visualization parameters
# ========================
visualization_params:
  - plot_tuning # plot tuning of data to training conditions
  - visualize_pc # plot point clouds in the PC space
  - plot_loss # plot loss
  - plot_box # plot log likelihood and operator norm comparisons